#!/usr/bin/env bash

# Script info
script_name="domoPicRename"
script_version="1.2"
script_tools="echo date figlet tput clear test mv exiftool awk tr"

########################
# Definition of colors #
########################

# General colors
color_off="\033[0m"
color_black="\033[0;30m"
color_red="\033[0;31m"
color_green="\033[0;32m"
color_yellow="\033[0;33m"
color_blue="\033[0;34m"
color_purple="\033[0;35m"
color_cyan="\033[0;36m"
color_white="\033[0;37m"
color_bold_black="\033[1;30m"
color_bold_red="\033[1;31m"
color_bold_green="\033[1;32m"
color_bold_yellow="\033[1;33m"
color_bold_blue="\033[1;34m"
color_bold_purple="\033[1;35m"
color_bold_cyan="\033[1;36m"
color_bold_white="\033[1;37m"

# Theme colors
color_header=$color_bold_red
color_time=$color_bold_purple
color_section=$color_bold_yellow
color_mark=$color_bold_white
color_error=$color_bold_red

########################
# Define exit function #
########################

# Function to end script with exit code and wait for ENTER to close window (if not started from shell)
function ScriptExit()
{
  if [ "$SCRIPT_STARTED_IN_X" = "1" ] || [ ! -z ${MC_SID+x} ]; then # Started in gnome-terminal or Midnight Commander?
    if [ "$1" -ne "0" ]; then
      echo -e "Exitcode $color_mark$1$color_off"
    fi
    echo
    echo -e "Press $color_mark""ENTER$color_off to close window"
    read
  fi

  if [ "$1" ]; then
    exit $1
  else
    exit
  fi
}

###############################
# Handle Terminal Environment #
###############################

if [ -t 0 ] && [ -t 1 ] && [ -t 2 ]; then # STDIN, STDOUT and STDERR defined?
  if [ ! -z ${MC_SID+x} ]; then # Started in Midnight Commander?
    clear
  fi
  echo -en "$color_off""Running $color_mark$script_name$color_off version $color_mark$script_version$color_off"
  if [ "$SCRIPT_STARTED_IN_X" = 1 ]; then
    echo -en " in $color_mark""X$color_off"
  else
    SCRIPT_STARTED_IN_X=0
    set -u # From her on warn about empty variables
    echo -en " in $color_mark""Terminal$color_off"
    if [ ! -z ${MC_SID+x} ]; then # Started in Midnight Commander?
      echo -en " started from $color_mark""mc$color_off"
    fi
  fi
  echo -en " as user $color_mark$(id -un)$color_off"
  if   [ $# -eq 1 ]; then
    echo -e " with parameter $color_mark$@$color_off"
  elif [ $# -gt 1 ]; then
    echo -en " with $color_mark$#$color_off parameters$color_mark"
    for x in "$@"; do
      echo -en " \"$x\""
    done
    echo -e "$color_off"
  else
    echo -e " with $color_mark""no$color_off parameters"
  fi
else
  # No Terminal found, starting gnome-terminal
  gnome-terminal --title $script_name" "$script_version -- /usr/bin/env "SCRIPT_STARTED_IN_X=1" "$0" "$@"
  exit
fi

####################
# Check Parameters #
####################

if [ $# -gt 0 ]; then # Parameter given?
  if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: picrename [OPTIONS] FILES"
    echo
    echo "picrename will take the EXIF date from the pictures and rename the file accordingly."
    echo
    echo "Options"
    echo "-h, --help      This help"
    echo "-d, --debug     print all executed commands"
    echo
    echo "Exit status:"
    echo " 0  if OK"
    echo " 1  if ERROR"
    ScriptExit 0
  elif [ "$1" = "--debug" ] || [ "$1" = "-d" ]; then
    set -x
    shift
  fi
fi

##########################
# Check for needed tools #
##########################

for x in $script_tools; do # Run through tool list
  which $x > /dev/null
  if [ $? -ne 0 ]; then
    echo -e "Tool $color_mark$x$color_off is missing!"
    ScriptExit 1
  fi
done

############################
# Show script startup info #
############################

echo -ne "$color_header"
figlet $script_name -w $(tput cols)
echo -e "$color_header$script_name $script_version$color_off"
echo

##########################
# Start time measurement #
##########################

echo -e "Starting $color_time$(date '+%Y-%m-%d %H:%M:%S')$color_off"
script_start=$(date '+%s')
echo

##########
# Script #
##########

filecount=$#
filenum=0
for oldfile in "$@"; do

  filenum=$((filenum+1))
  echo -ne "$color_section[$filenum/$filecount]$color_off "

  if [ ! -d "$oldfile" ]; then
    # Get name parts of old file
    filename="${oldfile##*/}"
    directory="${oldfile:0:${#oldfile} - ${#filename}}"
    basename="${oldfile%.[^.]*}"
    extension=$(echo "${oldfile:${#basename} + 1}" | tr [:upper:] [:lower:])

    # Get EXIF info and build new name
    exifdate=$(exiftool -CreateDate -d "%Y-%m-%d %H.%M.%S" "$oldfile" 2>/dev/null | awk '{print $4 " " $5}')
    newfile="$directory$exifdate.$extension"

    # Add number for same filenames
    num=1
    while [ -e "$newfile" ]; do
      if [ "$oldfile" != "$newfile" ]; then
        num=$((num+1))
        newfile="$directory$exifdate ($num).$extension"
      else
        break
      fi
    done

    # Handle file renaming
    if [ "$exifdate" != "" ]; then
      if [ "$exifdate" != "0000:00:00 00:00:00" ]; then
        if [ "$oldfile" != "$newfile" ]; then
          echo -e "Renaming $color_mark'"$(basename "$oldfile")"'$color_off to $color_mark'"$(basename "$newfile")"'$color_off"
          mv -n "$oldfile" "$newfile"  # -n -> do not overwrite an existing file
        else
          echo -e "$color_mark'"$(basename "$oldfile")"'$color_off has already the correct name!"
        fi
      else
        echo -e "$color_mark'"$(basename "$oldfile")"'$color_error has a bad EXIF Date!$color_off"
      fi
    else
      echo -e "$color_mark'"$(basename "$oldfile")"'$color_error has no EXIF Date!$color_off"
    fi
  else
    echo -e "$color_mark'"$(basename "$oldfile")"'$color_error is a directory!$color_off"
  fi

done

#########################
# Stop time measurement #
#########################

echo
echo -e "Finished $color_time$(date '+%Y-%m-%d %H:%M:%S')$color_off"
script_end="$(date '+%s')"
script_duration="$(( $script_end - $script_start ))"
echo -e "Duration $color_time$script_duration sec$color_off"
echo

###############
# Exit script #
###############

ScriptExit 0
