#!/usr/bin/env bash



# TODO: Make testfiles suitable for public use
# TODO: Add testfiles to git



SOURCE="./TestFiles"
TARGET="./TestArea"

echo "Cleaning up"
rm -r $TARGET/*

echo "Copying testfiles"
cp -rp $SOURCE/* $TARGET

echo "Running Program"
./picrename $TARGET/*

