#!/usr/bin/env bash

SOURCE="./TestFiles"
TARGET="./TestArea"

echo "Cleaning up"
rm -r $TARGET/*

echo "Copying testfiles"
cp -rp $SOURCE/* $TARGET

echo "Running Program"
./domopicrename $TARGET/*

